language: node_js
node_js:
- 8
cache:
  directories:
  - node_modules
script:
- gulp player
before_deploy:
- cd build
- tag=$(git tag --points-at $TRAVIS_COMMIT | tail -1)
- tar cf ../$tag.tar *
- cd ..
deploy:
  provider: releases
  api_key:
    secure: H5KkrWPf/hqPdvbZ+7NAbtf+F/vS0jn9jMrR4Yxq3qGmqAQswF5GSZzAKaYBtSlV5G98K/UwNzAIth3sQfIYIpanR1LG2Y3WyoWDI4rIL2Q8FeAxwLm5Cqhw73DS7crbtE86wr3OYSV8pIZ0pjqb82xatkluXGAJmDGhnc2usTQ41u5D5Muj/ke59xz0d7ajUjxIi331gFIVUSv8MydlDjD+vstsrKW+UOOm9FMay2Kyz7L8PJ1YRZdnO3pv/c6ewzLFAVLbfHsWWPiOdZQfQx5QAW41dN1g9xmxPOpMHT1q8wQk4QdR0NfizdUL+tKc+strmJ4NjSCFp5r4B5sT4cUlFz9RMNtApe+Cfx24gA6HZRs81nbUpG50RsoO8Oihwnd3+XLEZTSq0Y+QQIqUkP3wSUseRQwCHuZhZ4RbvldKsQ8s+YEBqCl3jEnuZzZ2Q3Y6TK72gSr/wxzaQI13UVXU4YyTdJQM0mblKXLNZVSQqwz9v2Ub2g8JEJ2UzTv7XpwOulsIWw4k3QmrGB47RAnShRb43Jrk3GUPElTMv80hsLRZF389lKzADblNxPiXwuKd1efYtDKOsg1ISkR3zegsH7UVZfw4Ygwkq3U1hDw1rhaX+EhgGLmEGBCk1CqNqnMJtWOiXLWp4L/mCl06fxctM1vGA9X/2x2nNYtzDQc=
  file: $tag.tar
  skip_cleanup: true
  on:
    tags: true
